defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:16
      environment:
        NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
        JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install pnpm -g
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test
      - run: npx codecov

workflows:
  version: 2
  all:
    jobs:
      - build
